nuke status-message-collections
near/near-sdk-rs pull request #1076
Opened 2023-08-19 11:40 UTC by shariffdev

Addresses: https://github.com/near/near-sdk-rs/issues/809

This PR eliminates the `status-message-collection` example, leaving only one `status-message`-esque example.

2023-08-21 10:20 UTC, uint requested changes
Hi! Unfortunately, this is not quite what we want here. We'd like there to be one `status-message` contract using the `LookupMap`.

`LookupMap` is more efficient (in the NEAR blockchain context) and the appropriate storage option to choose in situations like these. Since examples need to show contract devs best practices, we really need to advertise it over `HashMap` here.

2023-08-22 08:13 UTC, shariffdev commented
> Hi! Unfortunately, this is not quite what we want here. We'd like there to be one `status-message` contract using the `LookupMap`.
> 
> `LookupMap` is more efficient (in the NEAR blockchain context) and the appropriate storage option to choose in situations like these. Since examples need to show contract devs best practices, we really need to advertise it over `HashMap` here.

Understood, making chnages.

2023-08-23 11:51 UTC, uint approved these changes
LGTM!

2023-08-23 11:51 UTC, merged

2023-08-23 11:53 UTC, uint commented
@shariffdev One note: please include the phrase `Closes #539` when opening a PR for a specific issue. That way the issue gets automatically closed when we merge.