chore: bump syn crate from 1 to 2
near/near-sdk-rs pull request #1088
Opened 2023-09-30 20:42 UTC by iho

2023-10-02 11:19 UTC, iho commented
Hi @uint 
Can you review this PR, please?

2023-10-02 19:01 UTC, frol requested changes
Well, if all the tests pass, this seems safe to merge, but I still left a few comments to address before we merge this PR.

2023-10-02 19:01 UTC, frol commented on near-sdk-macros/src/core_impl/event/mod.rs
> +    };
```suggestion
    let args = MacroConfig::from_list(&attr_args).map_err(|err| 
        TokenStream::from(err.write_errors())
    )?;
```

2023-10-02 19:56 UTC, iho commented on near-sdk-macros/src/core_impl/event/mod.rs
> +    };
This function returns `TokenStream` instead of `Result`, so I can't do that.

2023-10-03 10:16 UTC, frol requested changes

2023-10-03 10:16 UTC, frol commented on near-sdk-macros/src/core_impl/info_extractor/arg_info.rs
> +                    // serializer_ty = serializer.serializer_type;
clean up

2023-10-03 10:16 UTC, frol commented on near-sdk/compilation_tests/schema_derive_invalids.stderr
> -   | |_^
In order to retain the test to check what it used to check, change the `#[abi(json, schemars)]` to just `#[abi(json)]`: https://github.com/near/near-sdk-rs/blob/9e79cea7b87f56a76f9f99f2d86fe646e631a4fc/near-sdk/compilation_tests/schema_derive_invalids.rs#L46

2023-10-03 10:16 UTC, frol commented on near-sdk/compilation_tests/schema_derive_invalids.stderr
> + --> $CARGO/schemars-0.8.13/src/gen.rs
Remove your local Cargo.lock and re-run the test again. I expect this change to be resolved.

2023-10-03 11:00 UTC, iho commented on near-sdk-macros/src/core_impl/info_extractor/arg_info.rs
> +                    // serializer_ty = serializer.serializer_type;
Thanks!

2023-10-04 06:15 UTC, frol approved these changes

2023-10-04 06:16 UTC, merged