feat: add screencast and new commands into read.me
near/near-sdk-rs pull request #1234
Opened 2024-08-06 09:30 UTC by juandiegocv27

# Enhance README with Screencast and Additional Commands

- Adding a [video tutorial](https://www.loom.com/share/2b5b4e61d8704fdd8ed402b92033784d?sid=ec126de5-b488-4d5a-9f0c-f55c431bb575) to help newcomers understand the project workflow, from setup to deployment.
- Including troubleshooting tips for function calls failing due to insufficient gas fees.
- Updating usage instructions with detailed commands for testing, building, and deploying NEAR smart contracts.

### Changes

1. **Usage Instructions:**
    - Added `cargo test` before `cargo near build`.
    - Included commands for `cargo near`, `cargo near build`, `cargo near create-dev-account`, `cargo near deploy`, and `cargo install near-cli-rs`.
    - Updated `near` command for contract selection and function calls.

2. **Video Tutorial:**
    - Added a link to the video tutorial.
    - Noted that the video shows a function call failure due to insufficient gas fees.

3. **Troubleshooting Section:**
    - Added tips for handling insufficient gas fees during function calls.
    - Provided examples for allocating sufficient gas and checking account balance.

related issue: [issue #1219](https://github.com/near/near-sdk-rs/issues/1219)

2024-08-06 09:31 UTC, juandiegocv27 commented
@frol ready for feedback!

2024-08-06 09:51 UTC, frol requested changes
Thanks for your attempt, but the result is not engaging. We need someone who can record and edit a video with nice transitions, highlights, and at least captions + music or voice-over.

2024-08-06 09:51 UTC, frol commented on README.md
> +```markdown
chatgpt...

2024-08-06 09:52 UTC, juandiegocv27 commented
> Thanks for your attempt, but the result is not engaging. We need someone who can record and edit a video with nice transitions, highlights, and at least captions + music or voice-over.

Ok sure, let me fix it and create a more engaging video 🔥🫡

2024-08-06 09:56 UTC, Jemiiah commented
@frol  i would love to work on this  if you allow it🌚

2024-08-06 19:11 UTC, juandiegocv27 commented on README.md
> +```markdown
what´s that?, im going to fix ir

2024-08-12 07:45 UTC, frol commented
@Jemiiah Oh, I missed your comment. If you are still interested in it, please, go ahead!

2024-08-12 07:56 UTC, Jemiiah commented
Hi Vlad,

Thanks for reaching out. I'm still interested and will proceed as
suggested. Excited to contribute further.



On Mon, Aug 12, 2024 at 12:45 AM Vlad Frolov ***@***.***>
wrote:

> @Jemiiah <https://github.com/Jemiiah> Oh, I missed your comment. If you
> are still interested in it, please, go ahead!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/near/near-sdk-rs/pull/1234#issuecomment-2283303178>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BGKR4UAXNX7SIJVBK2VT23LZRBR2NAVCNFSM6AAAAABMB5U26GVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDEOBTGMYDGMJXHA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-08-13 00:14 UTC, juandiegocv27 commented
@frol Ill finish this issue before tommorrow morning (less than 16 hours)

2024-08-14 19:54 UTC, frol commented
@juandiegocv27 Any updates on this front?

2024-08-14 19:56 UTC, juandiegocv27 commented
> @juandiegocv27 Any updates on this front?

im uploaading the video in youtube, finish the editing, in a couple of hours I'll put in the read.me

2024-08-15 08:57 UTC, juandiegocv27 commented
@frol finished and ready to merge, let me know

2024-08-21 10:48 UTC, juandiegocv27 commented
@frol sorry for the delay, editing videos is not my strong? can you assign this issue to someone else please

2024-08-21 10:48 UTC, closed without merging