Near sdk collections docs update
near/near-sdk-rs pull request #611
Opened 2021-10-19 11:27 UTC by deveusss

Updated docs for Vector, TreeMap, LookupSet, LookupMap, UnorderedMap, UnorderedSet

2021-10-19 15:09 UTC, austinabell requested changes

2021-10-19 15:09 UTC, austinabell commented on near-sdk/src/collections/tree_map.rs
> +    /// map.clear();
```suggestion
```

Don't really need this for this doc test

2021-10-19 15:09 UTC, austinabell commented on near-sdk/src/collections/tree_map.rs
> +    /// let mut map: TreeMap<u32, u32> = TreeMap::new(b"m".to_vec());
```suggestion
    /// let mut map: TreeMap<u32, u32> = TreeMap::new(b"m");
```

2021-10-19 15:09 UTC, austinabell commented on near-sdk/src/collections/tree_map.rs
> +    /// map.clear();
```suggestion
```

2021-10-19 15:09 UTC, austinabell commented on near-sdk/src/collections/tree_map.rs
> +    /// let mut map: TreeMap<u32, u32> = TreeMap::new(b"m".to_vec());
```suggestion
    /// let mut map: TreeMap<u32, u32> = TreeMap::new(b"m");
```

2021-10-19 15:09 UTC, austinabell commented on near-sdk/src/collections/tree_map.rs
> +    /// map.clear();
```suggestion
```

2021-10-19 15:09 UTC, austinabell commented on near-sdk/src/collections/tree_map.rs
> +    /// ///
```suggestion
    ///
```

2021-10-19 15:09 UTC, austinabell commented on near-sdk/src/collections/tree_map.rs
> +    /// let mut map: TreeMap<u32, u32> = TreeMap::new(b"m".to_vec());
```suggestion
    /// let mut map: TreeMap<u32, u32> = TreeMap::new(b"m");
```

2021-10-19 15:09 UTC, austinabell commented on near-sdk/src/collections/tree_map.rs
> +    ///     map.iter_from(29).collect::<Vec<(u32, u32)>>(),
optional: perhaps change this to iterating from 30 to show off the exclusive nature of the start index?

2021-10-19 15:09 UTC, austinabell commented on near-sdk/src/collections/tree_map.rs
> +    /// map.clear();
```suggestion
```

2021-10-19 15:09 UTC, austinabell commented on near-sdk/src/collections/tree_map.rs
> +    /// let mut map: TreeMap<u32, u32> = TreeMap::new(b"m".to_vec());
```suggestion
    /// let mut map: TreeMap<u32, u32> = TreeMap::new(b"m");
```

2021-10-19 15:09 UTC, austinabell commented on near-sdk/src/collections/tree_map.rs
> +    /// let two: Vec<u32> = vec![45, 35, 25, 15,
You're missing a closing brace here. Wondering why the need for two vectors if just indicating which keys to insert

2021-10-19 15:09 UTC, austinabell commented on near-sdk/src/collections/tree_map.rs
> +    ///
you probably need a `}` here, the loop above is not closed

2021-10-19 15:09 UTC, austinabell commented on near-sdk/src/collections/tree_map.rs
> +    /// map.clear();
```suggestion
```

2021-10-19 15:09 UTC, austinabell commented on near-sdk/src/collections/unordered_map.rs
> +    ///let mut set: LookupSet<u32> = LookupSet::new(b"m".to_vec());
```suggestion
    /// use near_sdk::collections::LookupSet;
    /// let mut set: LookupSet<u32> = LookupSet::new(b"m");
```

2021-10-19 15:09 UTC, austinabell commented on near-sdk/src/collections/unordered_set.rs
> +    ///let mut set: UnorderedSet<u32> = UnorderedSet::new(b"m".to_vec());
```suggestion
    /// use near_sdk::collections::UnorderedSet;
    /// let mut set: UnorderedSet<u32> = UnorderedSet::new(b"m");
```

2021-10-19 15:09 UTC, austinabell commented on near-sdk/src/collections/vector.rs
> +    ///let mut set: Vector<u32> = Vector::new(b"m".to_vec());
```suggestion
    /// use near_sdk::collections::Vector;
    /// let mut set: Vector<u32> = Vector::new(b"m");
```

2021-10-19 15:14 UTC, thedeveus commented on near-sdk/src/collections/lookup_map.rs
> +    /// }
sure, I will update to byte version)

2021-11-02 21:33 UTC, ChaoticTempest reviewed
`near-sdk/.DS_Store` and `near-sdk/src/.DS_Store` seems unnecessary to be adding to the repo. Best to remove those before merging this PR. Aside from that, just some minor stuff still left, but I'll leave it to @austinabell to approve and merge

2021-11-02 21:33 UTC, ChaoticTempest commented on near-sdk/src/collections/lookup_set.rs
> +    /// let mut set: LookupSet<u32> = LookupSet::new(b"m".to_vec());
```suggestion
    /// let mut set: LookupSet<u32> = LookupSet::new(b"m");
```

2021-11-02 21:33 UTC, ChaoticTempest commented on near-sdk/src/store/lookup_map/mod.rs
> +    /// assert_eq!(map[&1], "b");
```suggestion
    /// if let Some(x) = map.get_mut(&1) {
    ///     *x = "b";
    ///     assert_eq!(map[&1], "b");
    /// }
```

2021-11-05 14:06 UTC, austinabell commented
It seems you are still making additions. Can you let us know when you are done so we can review once, or consider making new additions in a new PR to break it up?

2021-11-11 19:12 UTC, thedeveus commented
> It seems you are still making additions. Can you let us know when you are done so we can review once, or consider making new additions in a new PR to break it up?
> 
> Thanks so much for adding all of these examples!

I think i finished with store collections, I am not sure if I need to add more examples in current collections

2021-11-17 16:36 UTC, austinabell commented
Not all doc tests are passing, if you run `cargo test` you should be able to see which ones to fix :)

2022-01-08 19:55 UTC, deveusss commented
> Not all doc tests are passing, if you run `cargo test` you should be able to see which ones to fix :)

fixed, thank you:)

2022-01-09 04:49 UTC, mikedotexe commented
Thanks @deveusss for doing this. Looks like we have a merge conflict to clean up

2022-03-04 19:15 UTC, austinabell commented
Is there anything I can do to help resolve conflicts and/or fix the CI? Seems like this PR has gone a bit stale

2022-03-07 21:00 UTC, deveusss commented
> 
yes, there is just two different version of examples and need to choose one) I ll fix this

2022-03-16 22:21 UTC, mikedotexe commented
Just updated the master and CI is running. we'd love to see this get in, and I'll ask @deveusss if everything is ready to go? I see there's a change requested currently

2022-04-13 14:24 UTC, merged